kind: pipeline
type: kubernetes
name: default

steps:
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: >
      Started build number {{build.number}}

- name: build
  image: node:16-alpine
  commands:
  - yarn
  - yarn build
