kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: node:16-alpine
  commands:
  - yarn
  - yarn build

- name: upload
  image: plugins/s3
  settings:
    bucket: pollux-build
    source: build/**/*
    target: ${DRONE_BUILD_NUMBER}
    path_style: true
    endpoint: https://play.minio.io:9000
